#!/usr/bin/env python

import pyexotica as exo
from pyexotica.publish_trajectory import *
from time import sleep
import sys
import numpy as np
import rospy
from geometry_msgs.msg import Point
from trajectory_msgs.msg import JointTrajectoryPoint, JointTrajectory
from std_srvs.srv import Trigger, TriggerResponse

class ik_outputter:

    def __init__(self):
        self.trajectory_time = 20.0
        self.ik = exo.Setup.load_solver('{wave_demo}/resources/nextage_ik.xml')
        self.ompl = exo.Setup.load_solver('{wave_demo}/resources/nextage_ompl.xml')
        self.solved = self.ik_solve()

    def ik_solve(self):
        self.ik.get_problem().set_rho('wave1', 1e3)
        self.ik.get_problem().set_rho('wave2', 0)
        self.wave1 = self.ik.solve()[0]

        self.ik.get_problem().set_rho('wave1', 0)
        self.ik.get_problem().set_rho('wave2', 1e3)
        self.wave2 = self.ik.solve()[0]

        print self.wave1
        print self.wave2

def main(args):
    rospy.init_node("wave_service")
    exo.Setup.init_ros()
    print("Solving the IK: ")
    wave = ik_outputter()

if __name__ == '__main__':
    main(sys.argv)